name: Build and Push Docker image

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate version from date
        id: date_version
        run: |
          VERSION=$(date +'%Y.%m.%d-%H%M')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build project with Gradle
        run: ./gradlew --info clean build --warning-mode all

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployment/Dockerfile
          push: true
          tags: |
            epareja97/technical_test_ms:${{ env.VERSION }}
            epareja97/technical_test_ms:latest
